const blogs = [
    {
        slug: '1',
        cover: '/space4.jpg',
        title: 'Dark Energy - The Greatest Mystery in the Universe',
        date: 'June 22, 2024',
        author: 'Nivedya Sudhir',
        para1: '', 
        para2: '', 
        para3: '', 
        para4: '', 
        para5: '', 
        image1: '',
        image2: '',
        image3: '',
    },
    {
        slug: '2',
        cover: '/space4.jpg',
        title: 'Dark Energy - The Greatest Mystery in the Universe',
        date: 'June 22, 2024',
        author: 'Nivedya Sudhir',
        para1: '', 
        para2: '', 
        para3: '', 
        para4: '', 
        para5: '', 
        image1: '',
        image2: '',
        image3: '',
    },
    {
        slug: '3',
        cover: '/space4.jpg',
        title: 'Dark Energy - The Greatest Mystery in the Universe',
        date: 'June 22, 2024',
        author: 'Nivedya Sudhir',
        para1: '', 
        para2: '', 
        para3: '', 
        para4: '', 
        para5: '', 
        image1: '',
        image2: '',
        image3: '',
    },
];

export default blogs;